export const ORDER_REQUEST = 'ORDER_REQUEST'
export const ORDER_SUCCESS = 'ORDER_SUCCESS'
export const ORDER_FAIL = 'ORDER_FAIL'

export const EMAIL_ORDER_REQUEST = 'EMAIL_ORDER_REQUEST'
export const EMAIL_ORDER_SUCCESS = 'EMAIL_ORDER_SUCCESS'
export const EMAIL_ORDER_FAIL = 'EMAIL_ORDER_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'